// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TranslationExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidTranslationExtensionPackageString = "0d6bc74b-746f-4204-82b6-c808a74be8dd";
        public static Guid guidTranslationExtensionPackage = new Guid(guidTranslationExtensionPackageString);

        public const string guidTranslationExtensionPackageCmdSetString = "b995e28d-3256-454b-94a7-67c3e4b94678";
        public static Guid guidTranslationExtensionPackageCmdSet = new Guid(guidTranslationExtensionPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int Command1Id = 0x0100;
        public const int cmdidCommand2 = 0x1021;
    }
}